package com.gradge.erp.auth.enums;

import java.util.Set;

public enum UserRole {
    SUPER_ADMIN(Set.of(
            "MANAGE_TENANTS", "MANAGE_SUBSCRIPTIONS", "APPROVE_EMPLOYEES", "VIEW_PLATFORM_METRICS",
            "MANAGE_BILLING", "VIEW_AUDIT_LOGS"
    )),
    OWNER(Set.of(
            "MANAGE_USERS", "VIEW_FINANCES", "RECORD_TRANSACTIONS", "MANAGE_PRODUCTS",
            "MANAGE_SUPPLIERS", "MANAGE_PURCHASES", "VIEW_REPORTS", "MANAGE_EMPLOYEES",
            "MANAGE_POS", "VIEW_POS_REPORTS", "MANAGE_INVENTORY", "MANAGE_HR", "MANAGE_PAYROLL",
            "MANAGE_ASSETS", "VIEW_ASSETS", "MANAGE_BILLING", "MANAGE_WORKSHOP",
            "VIEW_DASHBOARD", "EXPORT_REPORTS", "MANAGE_CUSTOMERS", "VIEW_AUDIT_LOGS"
    )),
    ADMIN(Set.of(
            "MANAGE_USERS", "VIEW_FINANCES", "RECORD_TRANSACTIONS", "MANAGE_PRODUCTS",
            "MANAGE_SUPPLIERS", "MANAGE_PURCHASES", "VIEW_REPORTS", "MANAGE_EMPLOYEES",
            "MANAGE_POS", "VIEW_POS_REPORTS", "MANAGE_INVENTORY", "MANAGE_HR", "MANAGE_PAYROLL",
            "MANAGE_ASSETS", "VIEW_ASSETS", "MANAGE_BILLING", "MANAGE_WORKSHOP",
            "VIEW_DASHBOARD", "EXPORT_REPORTS", "MANAGE_CUSTOMERS", "VIEW_AUDIT_LOGS"
    )),
    MANAGER(Set.of(
            "VIEW_FINANCES", "RECORD_TRANSACTIONS", "MANAGE_PRODUCTS", "MANAGE_SUPPLIERS",
            "MANAGE_PURCHASES", "VIEW_REPORTS", "MANAGE_POS", "VIEW_POS_REPORTS",
            "MANAGE_INVENTORY", "VIEW_ASSETS", "MANAGE_WORKSHOP", "VIEW_DASHBOARD",
            "EXPORT_REPORTS", "MANAGE_CUSTOMERS"
    )),
    CASHIER(Set.of(
            "RECORD_TRANSACTIONS", "MANAGE_POS", "VIEW_POS_REPORTS"
    )),
    STORE_KEEPER(Set.of(
            "MANAGE_PRODUCTS", "MANAGE_SUPPLIERS", "MANAGE_PURCHASES",
            "MANAGE_INVENTORY", "VIEW_ASSETS"
    )),
    ACCOUNTANT(Set.of(
            "VIEW_FINANCES", "RECORD_TRANSACTIONS", "VIEW_REPORTS",
            "VIEW_DASHBOARD", "EXPORT_REPORTS", "MANAGE_BILLING"
    )),
    HR_OFFICER(Set.of(
            "MANAGE_EMPLOYEES", "VIEW_REPORTS", "MANAGE_HR", "MANAGE_PAYROLL",
            "MANAGE_ASSETS", "VIEW_ASSETS", "VIEW_DASHBOARD"
    ));

    private final Set<String> permissions;

    UserRole(Set<String> permissions) {
        this.permissions = permissions;
    }

    public Set<String> getPermissions() {
        return permissions;
    }
}
