package com.gradge.erp.auth.enums;

public enum UserPermission {
    MANAGE_USERS,
    VIEW_FINANCES,
    RECORD_TRANSACTIONS,
    MANAGE_PRODUCTS,
    MANAGE_SUPPLIERS,
    MANAGE_PURCHASES,
    VIEW_REPORTS,
    MANAGE_EMPLOYEES,
    MANAGE_POS,
    VIEW_POS_REPORTS,
    MANAGE_INVENTORY,
    MANAGE_HR,
    MANAGE_PAYROLL,
    MANAGE_ASSETS,
    VIEW_ASSETS,
    MANAGE_BILLING,
    MANAGE_WORKSHOP,
    VIEW_DASHBOARD,
    EXPORT_REPORTS,
    MANAGE_CUSTOMERS,
    VIEW_AUDIT_LOGS
}
